import type { Contact, HazardousMaterial } from "./types"

export const hazardousMaterialsInfo: Record<
  HazardousMaterial,
  {
    name: string
    concentration: string
    toxicRange: string
    purpose: string
  }
> = {
  ammonia: {
    name: "암모니아 (NH₃)",
    concentration: "99.8%",
    toxicRange: "반경 500m",
    purpose: "탈질설비 환원제",
  },
  hydrochloric_acid: {
    name: "염산 (HCl)",
    concentration: "35%",
    toxicRange: "반경 300m",
    purpose: "수처리 pH 조절제",
  },
  byproduct_fuel_oil: {
    name: "부생연료유",
    concentration: "혼합물",
    toxicRange: "반경 200m",
    purpose: "보일러 연료",
  },
  hydrogen: {
    name: "수소 (H₂)",
    concentration: "99.9%",
    toxicRange: "반경 100m",
    purpose: "발전기 냉각가스",
  },
}

export const locationOptions = [
  "1호기 터빈 건물",
  "2호기 터빈 건물",
  "3호기 터빈 건물",
  "4호기 터빈 건물",
  "5호기 터빈 건물",
  "6호기 터빈 건물",
  "7호기 터빈 건물",
  "8호기 터빈 건물",
  "주제어동",
  "종합사무동",
  "암모니아 저장탱크",
  "염산 저장탱크",
  "부생연료유 저장탱크",
  "수소 공급설비",
  "냉각수 취수구",
  "배수처리장",
  "야적장",
  "변전소",
  "기타 위치",
]

export const incidentTypeOptions = [
  "화재",
  "폭발",
  "유해물질 누출",
  "정전",
  "설비 고장",
  "인명사고",
  "환경오염",
  "보안사고",
  "자연재해",
  "기타 비상상황",
]

export const mockContacts: Contact[] = [
  // 비상상황본부 주요 인원
  {
    id: "1",
    name: "황병소",
    phone: "010-7711-6581",
    role: "employee",
    department: "대표이사",
    emergencyRole: "commander",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "2",
    name: "권혁만",
    phone: "010-3571-6732",
    role: "employee",
    department: "발전기술본부장/전무",
    emergencyRole: "commander",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "3",
    name: "이종진",
    phone: "010-5509-9743",
    role: "employee",
    department: "원가관리부문장/상무",
    emergencyRole: "emergency_operation_manager",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "4",
    name: "권도우",
    phone: "010-8932-0537",
    role: "employee",
    department: "사업관리부문장/상무",
    emergencyRole: "emergency_operation_manager",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "5",
    name: "허창익",
    phone: "010-3160-0306",
    role: "employee",
    department: "경영관리부문장/상무",
    emergencyRole: "emergency_operation_manager",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "6",
    name: "정재훈",
    phone: "010-6238-7514",
    role: "employee",
    department: "DX실장/실장",
    isActive: true,
    building: "서울사무소",
  },
  {
    id: "7",
    name: "황정섭",
    phone: "010-7226-7170",
    role: "employee",
    department: "DX실",
    isActive: true,
    building: "서울사무소",
  },
  {
    id: "8",
    name: "고재문",
    phone: "010-4564-0394",
    role: "employee",
    department: "기술처장/상무보",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "9",
    name: "심재춘",
    phone: "010-4026-6050",
    role: "employee",
    department: "발전처장/상무보",
    isActive: true,
    building: "종합사무동",
  },

  // 기술총괄팀
  {
    id: "10",
    name: "신재호",
    phone: "010-6387-1167",
    role: "employee",
    department: "기술총괄팀장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "11",
    name: "송지헌",
    phone: "010-3133-4579",
    role: "employee",
    department: "기술총괄팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "12",
    name: "시형근",
    phone: "010-2537-3000",
    role: "employee",
    department: "기술총괄팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "13",
    name: "권승일",
    phone: "010-7770-2955",
    role: "employee",
    department: "기술총괄팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "14",
    name: "나미르",
    phone: "010-5664-0268",
    role: "employee",
    department: "기술총괄팀",
    isActive: true,
    building: "종합사무동",
  },

  // 발전설비팀
  {
    id: "15",
    name: "한정남",
    phone: "010-6371-4064",
    role: "employee",
    department: "발전설비팀장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "16",
    name: "김우영",
    phone: "010-9255-3031",
    role: "employee",
    department: "발전설비팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "17",
    name: "김태훈",
    phone: "010-2648-8893",
    role: "employee",
    department: "발전설비팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "18",
    name: "양상동",
    phone: "010-5034-6775",
    role: "employee",
    department: "발전설비팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "19",
    name: "전명석",
    phone: "010-7194-3524",
    role: "employee",
    department: "발전설비팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "20",
    name: "서우진",
    phone: "010-6567-8629",
    role: "employee",
    department: "발전설비팀",
    isActive: true,
    building: "주제어동",
  },

  // 발전팀
  {
    id: "21",
    name: "이승열",
    phone: "010-9471-2904",
    role: "employee",
    department: "발전팀장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "22",
    name: "백남억",
    phone: "010-8797-1123",
    role: "employee",
    department: "발전팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "23",
    name: "최태영",
    phone: "010-9904-2870",
    role: "employee",
    department: "발전팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "24",
    name: "이동호",
    phone: "010-4187-3027",
    role: "employee",
    department: "발전팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "25",
    name: "이정현",
    phone: "010-3379-4082",
    role: "employee",
    department: "발전팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "26",
    name: "김민지",
    phone: "010-6766-3430",
    role: "employee",
    department: "발전팀",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "27",
    name: "김태환",
    phone: "010-3716-4556",
    role: "employee",
    department: "발전팀",
    isActive: true,
    building: "주제어동",
  },

  // 발전팀 파트장들
  {
    id: "28",
    name: "윤지수",
    phone: "010-3032-3584",
    role: "employee",
    department: "발전팀 1파트장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "29",
    name: "곽종만",
    phone: "010-3838-7604",
    role: "employee",
    department: "발전팀 2파트장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "30",
    name: "임태헌",
    phone: "010-3594-5344",
    role: "employee",
    department: "발전팀 3파트장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "31",
    name: "이민우",
    phone: "010-9117-1563",
    role: "employee",
    department: "발전팀 4파트장",
    emergencyRole: "field_response_leader",
    isActive: true,
    building: "주제어동",
  },

  // 발전팀 1파트
  {
    id: "32",
    name: "엄휘용",
    phone: "010-2758-6308",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "33",
    name: "남경우",
    phone: "010-4035-6064",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "34",
    name: "이승수",
    phone: "010-5467-1835",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "35",
    name: "홍성복",
    phone: "010-5487-5027",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "36",
    name: "이정석",
    phone: "010-5113-4005",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "37",
    name: "안두형",
    phone: "010-2041-2058",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "38",
    name: "함경찬",
    phone: "010-2512-2689",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "39",
    name: "김정연",
    phone: "010-4781-6206",
    role: "employee",
    department: "발전팀 1파트",
    isActive: true,
    building: "주제어동",
  },

  // 발전팀 2파트
  {
    id: "40",
    name: "김선규",
    phone: "010-7131-6411",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "41",
    name: "김주혁",
    phone: "010-5032-3427",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "42",
    name: "박광현",
    phone: "010-6508-1604",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "43",
    name: "이강호",
    phone: "010-5377-2495",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "44",
    name: "김학림",
    phone: "010-8983-2256",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "45",
    name: "이종현",
    phone: "010-5183-1031",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "46",
    name: "박원재",
    phone: "010-5361-4971",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "47",
    name: "강선구",
    phone: "010-4575-0385",
    role: "employee",
    department: "발전팀 2파트",
    isActive: true,
    building: "주제어동",
  },

  // 발전팀 3파트
  {
    id: "48",
    name: "한태곤",
    phone: "010-3060-0921",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "49",
    name: "최효석",
    phone: "010-6233-5732",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "50",
    name: "이은석",
    phone: "010-3959-6290",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "51",
    name: "정연태",
    phone: "010-5127-3959",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "52",
    name: "변경호",
    phone: "010-5814-8521",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "53",
    name: "원진수",
    phone: "010-4337-4346",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "54",
    name: "김동현",
    phone: "010-7371-2539",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "55",
    name: "이은필",
    phone: "010-5699-0528",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "56",
    name: "최건희",
    phone: "010-7626-3179",
    role: "employee",
    department: "발전팀 3파트",
    isActive: true,
    building: "주제어동",
  },

  // 발전팀 4파트
  {
    id: "57",
    name: "안기호",
    phone: "010-9340-0510",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "58",
    name: "김치종",
    phone: "010-6737-4812",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "59",
    name: "최영수",
    phone: "010-5159-9620",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "60",
    name: "홍성우",
    phone: "010-3021-4850",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "61",
    name: "윤상현",
    phone: "010-6563-1348",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "62",
    name: "김형석",
    phone: "010-7417-3800",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "63",
    name: "김재준",
    phone: "010-2432-8262",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "64",
    name: "권영진",
    phone: "010-7775-5997",
    role: "employee",
    department: "발전팀 4파트",
    isActive: true,
    building: "주제어동",
  },

  // 환경설비팀
  {
    id: "65",
    name: "이효승",
    phone: "010-4946-0519",
    role: "employee",
    department: "환경설비팀장",
    emergencyRole: "initial_response_leader",
    isActive: true,
    building: "용수환경동",
  },
  {
    id: "66",
    name: "권길성",
    phone: "010-8744-5389",
    role: "employee",
    department: "환경설비팀",
    isActive: true,
    building: "용수환경동",
  },
  {
    id: "67",
    name: "안재원",
    phone: "010-8360-6540",
    role: "employee",
    department: "환경설비팀",
    isActive: true,
    building: "용수환경동",
  },
  {
    id: "68",
    name: "공상훈",
    phone: "010-2386-9107",
    role: "employee",
    department: "환경설비팀",
    isActive: true,
    building: "용수환경동",
  },
  {
    id: "69",
    name: "박준용",
    phone: "010-4914-1608",
    role: "employee",
    department: "환경설비팀",
    isActive: true,
    building: "용수환경동",
  },
  {
    id: "70",
    name: "최민권",
    phone: "010-2255-6337",
    role: "employee",
    department: "환경설비팀",
    isActive: true,
    building: "용수환경동",
  },
  {
    id: "71",
    name: "민재훈",
    phone: "010-3371-6343",
    role: "employee",
    department: "환경설비팀",
    isActive: true,
    building: "용수환경동",
  },

  // 안전팀
  {
    id: "72",
    name: "이원형",
    phone: "010-2773-3802",
    role: "employee",
    department: "안전팀장",
    emergencyRole: "emergency_contact_leader",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "73",
    name: "박정원",
    phone: "010-4727-6730",
    role: "employee",
    department: "안전팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "74",
    name: "전상훈",
    phone: "010-3008-8220",
    role: "employee",
    department: "안전팀",
    emergencyRole: "emergency_contact_leader",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "75",
    name: "송기태",
    phone: "010-2566-5222",
    role: "employee",
    department: "안전팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "76",
    name: "윤주은",
    phone: "010-3419-2024",
    role: "employee",
    department: "안전팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "77",
    name: "주용준",
    phone: "010-9509-5459",
    role: "employee",
    department: "안전팀",
    isActive: true,
    building: "종합사무동",
  },

  // 연료구매팀
  {
    id: "78",
    name: "장강석",
    phone: "010-3628-7563",
    role: "employee",
    department: "연료구매팀장",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "79",
    name: "고현우",
    phone: "010-2756-5388",
    role: "employee",
    department: "연료구매팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "80",
    name: "이민주",
    phone: "010-6450-6889",
    role: "employee",
    department: "연료구매팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "81",
    name: "정상훈",
    phone: "010-6615-6033",
    role: "employee",
    department: "연료구매팀",
    isActive: true,
    building: "종합사무동",
  },

  // 사업지원팀
  {
    id: "82",
    name: "이재혁",
    phone: "010-3198-0469",
    role: "employee",
    department: "사업지원팀장",
    emergencyRole: "pr_leader",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "83",
    name: "서현우",
    phone: "010-4550-3301",
    role: "employee",
    department: "사업지원팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "84",
    name: "이보람",
    phone: "010-2723-6355",
    role: "employee",
    department: "사업지원팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "85",
    name: "김원상",
    phone: "010-9925-2011",
    role: "employee",
    department: "사업지원팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "86",
    name: "유종민",
    phone: "010-6486-9963",
    role: "employee",
    department: "사업지원팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "87",
    name: "최일권",
    phone: "010-4819-7604",
    role: "employee",
    department: "사업지원팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "88",
    name: "김민",
    phone: "010-9870-9697",
    role: "employee",
    department: "사업지원팀",
    isActive: true,
    building: "종합사무동",
  },

  // 전력시장팀
  {
    id: "89",
    name: "이승현",
    phone: "010-9267-9705",
    role: "employee",
    department: "전력시장팀장",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "90",
    name: "김유신",
    phone: "010-5330-2240",
    role: "employee",
    department: "전력시장팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "91",
    name: "조동희",
    phone: "010-7106-7570",
    role: "employee",
    department: "전력시장팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "92",
    name: "박주호",
    phone: "010-3711-4670",
    role: "employee",
    department: "전력시장팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "93",
    name: "김진하",
    phone: "010-9768-0718",
    role: "employee",
    department: "전력시장팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "94",
    name: "온소정",
    phone: "010-2578-5734",
    role: "employee",
    department: "전력시장팀",
    isActive: true,
    building: "종합사무동",
  },

  // 기후변화대응팀
  {
    id: "95",
    name: "손현우",
    phone: "010-5201-8055",
    role: "employee",
    department: "기후변화대응팀장",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "96",
    name: "김익환",
    phone: "010-2486-8979",
    role: "employee",
    department: "기후변화대응팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "97",
    name: "이예리",
    phone: "010-4429-8685",
    role: "employee",
    department: "기후변화대응팀",
    isActive: true,
    building: "종합사무동",
  },
  {
    id: "98",
    name: "김유라",
    phone: "010-2609-9509",
    role: "employee",
    department: "기후변화대응팀",
    isActive: true,
    building: "종합사무동",
  },

  // 협력사 - 오르비스
  {
    id: "101",
    name: "김협력",
    phone: "010-1111-1111",
    role: "contractor",
    company: "오르비스",
    department: "정비",
    isActive: true,
    building: "터빈동",
  },
  {
    id: "102",
    name: "박정비",
    phone: "010-2222-2222",
    role: "contractor",
    company: "일진파워",
    department: "전기",
    isActive: true,
    building: "전기실",
  },
  {
    id: "103",
    name: "이운전",
    phone: "010-3333-3333",
    role: "contractor",
    company: "한전산업개발",
    department: "운전",
    isActive: true,
    building: "주제어동",
  },
  {
    id: "104",
    name: "최환경",
    phone: "010-4444-4444",
    role: "contractor",
    company: "수산인더스트리",
    department: "환경",
    isActive: true,
    building: "용수환경동",
  },
]

export const mockIncidents = [
  {
    id: "1",
    location: "암모니아 저장탱크",
    type: "유해물질 누출",
    hazardousMaterial: "ammonia" as HazardousMaterial,
    description: "M-TK-01A 암모니아 탱크 밸브 파손으로 외부누출 발생",
    reportedAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2시간 전
    reportedBy: "발전팀 1파트 윤지수",
    status: "active" as const,
    alertLevel: "yellow" as const,
    notificationsSent: 47,
    contactsNotified: ["1", "2", "21", "28"],
    evacuationRequired: true,
    affectedArea: "반경 320m (독성피해범위 ERPG 2)",
    estimatedDamage: "수억원 (화재 시)",
    recoveryTime: "3개월 (화재 시)",
  },
  {
    id: "4",
    location: "암모니아 저장탱크",
    type: "유해물질 누출",
    hazardousMaterial: "ammonia" as HazardousMaterial,
    description:
      "M-TK-01B 암모니아 저장탱크 상부 배관 연결부 플랜지에서 누출 감지. 현장 작업자가 자극성 냄새 감지 후 즉시 신고. 누출량 약 5kg/hr 추정. 현재 탱크 압력 8.5 bar, 온도 -33°C 정상 범위 내 유지 중.",
    reportedAt: new Date(Date.now() - 15 * 60 * 1000), // 15분 전
    reportedBy: "발전팀 3파트 임태헌",
    status: "pending_approval" as const,
    alertLevel: "yellow" as const,
    notificationsSent: 0,
    contactsNotified: [],
    evacuationRequired: true,
    affectedArea: "반경 500m (독성피해범위)",
    estimatedDamage: "수천만원 (즉시 조치 시)",
    recoveryTime: "1주일 (즉시 조치 시)",
  },
  {
    id: "2",
    location: "복수탈염 염산저장탱크",
    type: "유해물질 누출",
    hazardousMaterial: "hydrochloric_acid" as HazardousMaterial,
    description: "M-TK-11A 염산 35% 저장탱크 밸브 파손으로 외부누출",
    reportedAt: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6시간 전
    reportedBy: "환경설비팀 이효승",
    status: "resolved" as const,
    alertLevel: "blue" as const,
    notificationsSent: 23,
    contactsNotified: ["65", "72", "73"],
    evacuationRequired: false,
    affectedArea: "반경 266m (독성피해범위 ERPG 2)",
    estimatedDamage: "수천만원",
    recoveryTime: "0.5개월",
  },
  {
    id: "3",
    location: "부생연료유 탱크",
    type: "화재",
    hazardousMaterial: "byproduct_fuel_oil" as HazardousMaterial,
    description: "부생연료유 탱크 하부 밸브 파손으로 누출 후 화재 발생",
    reportedAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1일 전
    reportedBy: "발전팀 2파트 곽종만",
    status: "resolved" as const,
    alertLevel: "red" as const,
    notificationsSent: 89,
    contactsNotified: ["1", "2", "21", "29", "72"],
    evacuationRequired: true,
    affectedArea: "복사열피해범위 64m (4 kW/m²)",
    estimatedDamage: "수억원",
    recoveryTime: "3개월",
  },
]

// Alert level information
export const alertLevelInfo = {
  white: { name: "백색경보", color: "white", description: "경미한 상황" },
  blue: { name: "청색경보", color: "blue", description: "주의 상황" },
  yellow: { name: "황색경보", color: "yellow", description: "경계 상황" },
  red: { name: "적색경보", color: "red", description: "심각한 상황" },
}

// Evacuation sites
export const evacuationSites = [
  { name: "동해시민체육관", address: "강원도 동해시 천곡동", capacity: 1000 },
  { name: "동해문화예술회관", address: "강원도 동해시 송정동", capacity: 500 },
  { name: "북평초등학교", address: "강원도 동해시 북평동", capacity: 800 },
]

// Alert message templates
export const alertMessageTemplates = {
  fire: "화재 발생으로 인한 비상상황입니다. 즉시 대피하세요.",
  explosion: "폭발 사고가 발생했습니다. 안전한 곳으로 대피하세요.",
  chemical_leak: "유해물질 누출이 발생했습니다. 호흡기 보호 후 대피하세요.",
  evacuation: "전체 대피 명령이 발령되었습니다. 지정된 대피소로 이동하세요.",
}
